# -*- coding: utf-8 -*-
"""student _analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wB34KsV6yj7O33HKzWh3Tb87o3rBcKhB
"""

import numpy as np

marks = np.array([
    [78, 85, 92, 88],   # Student 1
    [65, 70, 60, 72],   # Student 2
    [90, 95, 94, 98],   # Student 3
    [45, 55, 50, 48],   # Student 4
    [88, 82, 80, 85]    # Student 5
])

print(marks)

print("shape of  array:", marks.shape) #5 studets 4 subjects

print("INDEXING")
print(marks[2][3])

print("Slicing")
print(marks[2]) # student 3
print(marks[:,1])
print(marks[1:4])

"""ANALYSIS"""

print("AVG per student")
student_avg = np.mean(marks,axis=1)
print(student_avg)

print("AVG per subject")
sub_avg = np.mean(marks,axis=0)
print(sub_avg)

print("TOPPER")
topper = np.argmax(student_avg)
print("Topper is student:",topper+1)

print("Weakest")
weakest = np.argmin(student_avg )
print("weakest student:", weakest+1)

res = np.where(student_avg >= 60,"Pass","Fail")
print(res)

grades = np.where(student_avg>=90,"A",
                  np.where(student_avg >=75,"B",
                  np.where(student_avg >=60,"C","Fail")))

print(grades)

print("Toughest subject")
Toughest = np.argmin(sub_avg)
print("Toughest suject index:",Toughest+1)

pass_cnt = np.sum(student_avg >= 60)
fail_cnt = np.sum(student_avg < 60)

print("pass students:", pass_cnt)
print("fail students:",fail_cnt)

total_student = len(student_avg)

print("pass %: ", (pass_cnt/total_student)*100)
print("fail %: ", (fail_cnt/total_student)*100)

summary = {
    "student_average": student_avg,
    "grades": grades,
    "topper": topper + 1,
    "weakest_student": weakest + 1,
    "toughest_subject": Toughest + 1,
    "pass_percentage": (pass_cnt / total_student) * 100
}

summary

print("Analysis completed successfully.")